Type: AWS::CloudFront::Function
Properties:
  Name:
    Fn::Sub: ${self:custom.bucketName}-request
  FunctionConfig:
    Comment:
      Fn::Sub: ${self:custom.bucketName}-request
    Runtime: cloudfront-js-1.0
  AutoPublish: true
  FunctionCode:
    Fn::Sub: |
      // CloudFront Function for Basic Auth and SPA redirect
      var REDIRECT_REGEX = /^[^.]+$|\.(?!(css|gif|ico|jpg|jpeg|js|png|txt|svg|woff|woff2|ttf|map|json|webp|xml|pdf|webmanifest|avif|wasm)$)([^.]+$)/;

      function handler(event) {
        var request = event.request;
        var uri = request.uri;
        var headers = request.headers;

        // Redirect for SPA routing
        if (REDIRECT_REGEX.test(uri)) {
          request.uri = "/index.html";
        }
        if (uri === '/manifest.json') {
          return request;
        }

        // Read credentials from environment variables (replace at deploy time)
        var authUser = process.env.AUTH_USER || '';
        var authPass = process.env.AUTH_PASS || '';
        var tmp = authUser + ':' + authPass;
        var authString = 'Basic ' + Buffer.from(tmp).toString('base64');

        // Check Authorization header
        if (
          typeof headers.authorization === "undefined" ||
          headers.authorization.value !== authString
        ) {
          return {
            statusCode: 401,
            statusDescription: "Unauthorized",
            headers: { "www-authenticate": { value: "Basic" } }
          };
        }
        return request;
      }
