Type: AWS::CloudFront::Distribution
Properties:
  DistributionConfig:
    Enabled: true
    HttpVersion: http2and3
    Aliases:
      - ${param:DOMAIN_ALIASES}
    PriceClass: PriceClass_100
    WebACLId: ${param:AWS_CLOUDFRONT_WAF_NAME}
    Origins:
      - Id: ${self:custom.bucketName}
        DomainName:
          Fn::Join:
            - "."
            - - Ref: Bucket
              - s3
              - Ref: AWS::Region
              - Ref: AWS::URLSuffix
        OriginAccessControlId:
          Ref: OriginAccessControl
        S3OriginConfig:
          OriginAccessIdentity: ""
    DefaultCacheBehavior:
      TargetOriginId: ${self:custom.bucketName}
      ViewerProtocolPolicy: https-only
      ForwardedValues:
        QueryString: false
      FunctionAssociations:
        - EventType: viewer-request
          FunctionARN: !GetAtt CloudFrontFunctionRequest.FunctionARN
        - EventType: viewer-response
          FunctionARN: !GetAtt CloudFrontFunctionResponse.FunctionARN
    CustomErrorResponses:
      - ErrorCode: 403
        ResponsePagePath: /404.html
        ResponseCode: 404
        ErrorCachingMinTTL: 300
      - ErrorCode: 404
        ResponsePagePath: /404.html
        ResponseCode: 404
        ErrorCachingMinTTL: 300
    ViewerCertificate:
      AcmCertificateArn: ${param:AWS_ACM_CERTIFICATION_ARN}
      SslSupportMethod: sni-only
      MinimumProtocolVersion: TLSv1.2_2021
