Type: AWS::CloudFront::Function
Properties:
  Name:
    Fn::Sub: ${self:custom.bucketName}-request
  FunctionConfig:
    Comment:
      Fn::Sub: ${self:custom.bucketName}-request
    Runtime: cloudfront-js-1.0
  AutoPublish: true
  FunctionCode:
    Fn::Sub: |
      // CloudFront Function (ES 5.1 syntax)
      function handler(event) {
          var request = event.request;
          var uri = request.uri;

          // Check if URI ends with a slash '/'
          if (uri.endsWith('/')) {
              request.uri += 'index.html';
          }
          // Check if URI appears to be a directory (lacks a file extension)
          // This simple check assumes file extensions have a dot. Adjust if needed.
          else if (!uri.includes('.')) {
              request.uri += '/index.html';
          }

          return request;
      }
