name: push

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  ENVIRONMENT: develop
  AWS_REGION: ap-northeast-1

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: npm ci
        run: npm ci

      - name: npm lint
        run: npm run lint

      - name: npm run format
        run: npm run format

      - name: build
        run: npm run build
        env:
          CI: false
